### ISSUE TITLE
Using an exit node

### ISSUE THREAD

**Issue by EPeterE** [hassio-addons/addon-tailscale#121]
Hi
Is there an option to allow Tailscale to route traffic via an exit node in the addon?

**Comment by sawasy** [comment]
If you look at the machine, once connected, in the Tailscale Dashboard, there is a 'review' button. Options under this button will allow you to enable 'exit node'.

m!

**Comment by EPeterE** [comment]
Hi
I don't want to use it as an exit node, I want to route all traffic via an
exit node, so I want to be able to specify an exit node to use. Much like
the other Linux, android, windows apps.
Thanks

**Comment by Mincka** [comment]
Have a look at this alternative addon:
https://github.com/tsujamin/hass-addons/tree/main/tailscale

This one allows you to specify specific IP address for the exit node.

**Comment by EPeterE** [comment]
Have you actually used this add-on? I installed it and it appeared to work,
and register on my tailscale admin panel. Then I added the IP address for
the exit node and it refused to save and now HA wan't load my supervisor
panel.
Any idea how to recover that now?

**Comment by Mincka** [comment]
Sorry to hear you ran into an issue.
I actually use this addon with the exit node advertisement and it works great. I don't use this specific IP address exit node option. 
You can try to connect to HA over SSH and use the CLI to stop the addon. If you didn't check "Start on boot" you can also just reboot.

**Comment by EPeterE** [comment]
Hi using an exit node cause tailscale to hang on other systems too. I
installed tailscale on a GL.iNet300M router and soon as you activate exit
node, you have to physically reset router to factory settings.
Unfortunately SSH is no longer work, nor is the ADD-ON or back up menus.
They say the supervisor panel hasn't loaded

**Comment by Mincka** [comment]
With or without specifying an IP for the exit node?
Was it already enabled as an exit node in Tailscale interface, or does it hang only the advertisement of the exit node?
I think you should create an issue on the dedicated repository.
You can have a look at the developer SSH setup:
https://developers.home-assistant.io/docs/operating-system/debugging/
Otherwise, your best bet to recover is to reinstall and restore a backup I guess. If you don't have one yet, I recommend the Google Backup Add-on. Good luck.

**Comment by EPeterE** [comment]
No, using an exit node as opposed to advertising as an exit node causes
problems
