### ISSUE TITLE
Update to latest Tailscal version

### ISSUE THREAD

**Issue by R0yk3** [hassio-addons/addon-tailscale#246]
# Problem/Motivation

> I see that there is code changed to update tailscale to version 1.48.1, but how do i get my instance to use that version. I'm stil runing version 1.38.4, with the addon version 0.11.1

## Expected behavior

> Update addon, or restart and take over new code.

## Actual behavior

> no auto update

## Steps to reproduce

>

## Proposed changes

> Explanation by how to update tailscale without updating the addon.

**Comment by lmagyar** [comment]
#181 introduced a blocking issue (two nodes advertising the same eg. 192.168.x.x subnet and turning on subnet routing makes HA unable to reach local network, "soft bricking" it), that's why there are no new releases of this add-on.

#201 is a possible workaround for this blocking issue.

Until this issue is resolved here, try my fork, where there is a workaround for this blocking issue, all the unreleased changes are available, and there are some extra config options: https://github.com/lmagyar/homeassistant-addon-tailscale

Note: I'm just another user

**Comment by davralin** [comment]
Does the "not planned"-closage mean we should abandon this addon, switch to @Imagyar's fork, or run with unpatched software?

Yes, I know that was just github-actions, but an issue for "updating to latest tailscale-version" closed as "not-planned", while being so significantly behind on versioning doesn't really send out the best signal.
