### ISSUE TITLE
Can not connect to remote OpenMediaVault server over TailScale

### ISSUE THREAD

**Issue by lsteck** [hassio-addons/addon-tailscale#248]
# Problem/Motivation
I have a remote OpenMediaVault (OMV) server that I'd like to connect to using the `https://github.com/tomaae/homeassistant-openmediavault`  integration and this tailscale-addon but it doesn't work.  It states there is not response from my OMV server.  I'm using the Tailscale IP of the server when I configure it.  I can connect to my Home Assistant server remotely using Tailscale so that connection is working. I am about to connect Home Assistant to local OMV servers using the OVM integration.

## Expected behavior
I should be able to connect to my OVM remote server using OMV integration and this addon.
I can connect to my OVM remote server using Tailscale on another client (server).  I should be able to connect to it from my Home Assistant server.

## Actual behavior

This the the error I'm seeing.  I `X`ed out the IP address but I'm entering my Tailscale IP address
<img width="625" alt="image" src="https://github.com/hassio-addons/addon-tailscale/assets/3800155/a40d2b65-4470-42a7-92fb-b15a983e4817">

## Steps to reproduce
Install the OpenMediaValut integration the the TailScale addon. and try to configure the OMV integration to connect to the OMV server

**Comment by lmagyar** [comment]
If you want an outgoing connection, you need a `tailscale0` interface, but the last released version of this add-on runs in userspace-networking mode, so no `tailscale0` interface is available, so it is not possible to route outgoing traffic.

#181 dropped userspace networking, but introduced a blocking issue (two nodes advertising the same eg. 192.168.x.x subnet and turning on subnet routing makes HA unable to reach local network, "soft bricking" it), that's why there are no new releases of this add-on.

#201 is a possible workaround for this blocking issue. Unmerged.

Until this issue is resolved here, try my fork, where there is a workaround for this blocking issue, all the unreleased changes are available, and there are some extra config options: https://github.com/lmagyar/homeassistant-addon-tailscale

Note: I'm just another user

**Comment by hallerdavid** [comment]
The problem still exists. I can also not ping tailnet devices. Trying to connect two Home Assistant via Remote.

**Comment by lmagyar** [comment]
Yes, the last released version doesn't support this, see my comment above (TLDR: try my fork at https://github.com/lmagyar/homeassistant-addon-tailscale).

**Comment by lmagyar** [comment]
> i have read this, and i tried also your fork but it stuck in an never ending loop between "connected" and not :-( reconnects every few seconds.

Please open an issue in my repo with your log, it should work, let's figure out the problem.

**Comment by hallerdavid** [comment]
can you tell me how i can get the log?

**Comment by lmagyar** [comment]
After v0.12.0 is released, this issue can be closed (new version is capable to use tun instead of userspace-networking).
