### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by Weldawadyathink** [hassio-addons/addon-tailscale#62]
HTTPS Support

https://tailscale.com/kb/1153/enabling-https/

Is it possible to add support for requesting an SSL certificate with Tailscale?

**Comment by franzbischoff** [comment]
There is a requirement on current version: https://issueexplorer.com/issue/tailscale/tailscale/2932

Fix: 
create a folder at /data/tailscale
edit `/etc/services.d/tailscaled/run`
change `options+=(--state=/data/tailscaled.state)` to `options+=(--state=/data/tailscale/tailscaled.state)`
copy the current `/data/tailscaled.state` to `/data/tailscale/tailscaled.state` to keep login etc.
restart service: `s6-svc -r /var/run/s6/services/tailscaled`

now you can run `/opt/tailscale cert yourmachine.yourdomain.ts.net`

**Comment by benley** [comment]
> There is a requirement on current version: https://issueexplorer.com/issue/tailscale/tailscale/2932

I get a 404 on that link, but I think this is the issue in question: https://github.com/tailscale/tailscale/issues/2932

**Comment by franzbischoff** [comment]
Just made a Gist for that.

Use at your own risk:

[tailscale hack](https://gist.github.com/franzbischoff/1dc960aa5ad93c604f1cc57282f3ebb4)

**Comment by ananthb** [comment]
Would it make sense to add this as a config option?

**Comment by franzbischoff** [comment]
For me makes total sense. To be able to move from using an external port on my router to access HA with my phone, for example, I use HTTPS and the tailscale "domain" with the provided certificate.

**Comment by ananthb** [comment]
@frenck could you take a look at my PR? Would love to get this merged soon!

**Comment by benley** [comment]
not stale

**Comment by ananthb** [comment]
Still being worked on.

**Comment by benley** [comment]
still not stale

**Comment by franzbischoff** [comment]
not stale!

**Comment by martusi61** [comment]
I'm waiting too!

**Comment by franzbischoff** [comment]
nooooooooooot stale

**Comment by ceiphr** [comment]
not stale

**Comment by stroodle96** [comment]
Also hoping this gets added.

**Comment by Mincka** [comment]
You can have a look at this alternative addon which seems to provide https support:
https://github.com/tsujamin/hass-addons/tree/main/tailscale
https://github.com/tsujamin/hass-addons/blob/main/tailscale/DOCS.md#option-cert_domain

**Comment by elcajon** [comment]
I made another suggestion to set Tailscale up with https support for Home Assistant (without manually handling the certificate and key files --> so still "zero config"). Feel free to give it a try #123

**Comment by ceiphr** [comment]
not stale

**Comment by lmagyar** [comment]
It has a working implementation as a PR, so it is not stale.

Though there is a new (currently alpha) Tailscale feature called Funnel, that seems to be an even better solution:
- Tailscale provides an internet->VPN proxy, so you don't need to install a Tailscale client on your phone, laptop, etc.
- It is dual opt-in, so can be turned on by default (like exit node, subnet features)
- After I test it I will create another PR for this Funnel feature

**Comment by lmagyar** [comment]
And now this HTTPS problem has a much better solution, though no PR yet, because the Tailscale feature is still alpha.

My previous solution PR #134 (that you can try at https://github.com/lmagyar/homeassistant-addon-tailscale) downloaded a certificate and we had to use it.

---

But @elcajon notified me about a new feature, Tailscale Funnel:
- built in https proxy in the Tailscale client
- TCP proxy on the Tailscale servers from the internet into our VPN
- so you can access HA from a general browser, even without an installed Tailscale client

**Client** &#8658; _Internet_ &#8658; **Tailscale Funnel** (TCP Proxy) &#8658; _VPN_ &#8658; **Tailscale Proxy** (https proxy) &#8594; **HA** (http web-server)

---

I modified his solution into a no-config add-on version, that you can try in my other repo: https://github.com/lmagyar/homeassistant-addon-tailscale-funnel

This should replace my previous solution, but the Tailscale Funnel feature is still in alpha, so I prefer not to make a PR yet.

You need an invite to test the Funnel feature: https://login.tailscale.com/admin/feature/rWXbjRuCEc9 (first 10 people can use it, and those 10 can invite 10 x 10 other "tester"...).

But without the Funnel, the add-on starts at least the built in Proxy, and logs a warning about the missing Funnel.

**Comment by ShadowJonathan** [comment]
Tailscale funnel could indeed solve a huge part of this problem, but it would step on the toes, or basically trample, the Home Assistant Cloud offering, so i'm not confident that HA will entirely embrace something like that

**Comment by lmagyar** [comment]
I've made a PR with the built-in https proxy instead of the manual certificate download in #89 #134.

This doesn't involve the still alpha funnel feature, but at least a no-config solution for the https support.

**Comment by lmagyar** [comment]
FYI:
- The Tailscale Proxy feature (mentioned in the above pr #137, that replaces the certificate download) is accessible in my fork: https://github.com/lmagyar/homeassistant-addon-tailscale
- If somebody is interested in the additional Tailscale Funnel (alpha) feature, it is accessible in my other fork: https://github.com/lmagyar/homeassistant-addon-tailscale-funnel

**Comment by lmagyar** [comment]
not stale

**Comment by frenck** [comment]
Closing this issue, as it is a feature request and not en issue/bug report.

../Frenck

**Comment by ananthb** [comment]
LOL

**Comment by franzbischoff** [comment]
The most requested featured I've seen, closed :-D
