### ISSUE TITLE
Memory leak/high memory usage, possibly with 1.20.0?

### ISSUE THREAD

**Issue by kevin-david** [hassio-addons/addon-tailscale#71]
# Problem/Motivation
My home assistant OS based machine has been crashing/locking up overnight the past few nights, seemingly because of an out-of-memory condition. When I connected to the console, I noticed `tailscaled` was getting killed.

![foto_no_exif](https://user-images.githubusercontent.com/1923186/149673413-313d9679-5800-4bbc-90fd-c7607a150c20.jpg)

The timing _seems_ to coincide with the upgrade to 1.20.0 a few days ago and I do have auto upgrade enabled.

I am not 100% sure where to report this - here or to tailscale - but figured I'd start here...

Secondary question: is there a way to configure the OOM killer or swapfile so this _doesn't_ happen and crash my machine?

## Expected behavior

Normal memory usage.

## Actual behavior

Initial memory usage:
![image](https://user-images.githubusercontent.com/1923186/149673355-ef689fe1-a97f-42d0-be0c-ecb5d846f2ec.png)

After a few hours (sorry about the phone screenshot, but set up an automation to catch it)
![Screenshot_20220117-000925](https://user-images.githubusercontent.com/1923186/149787800-2acfb84d-6eab-457b-868c-815b5314b0bb.png)
![Screenshot_20220117-000819](https://user-images.githubusercontent.com/1923186/149787803-fe10b697-de72-4280-be53-a90266ad1e7d.png)

There is nothing really in the log that I can see - but happy to go elsewhere and get more OS logs. 

## Steps to reproduce

Upgrade to 1.20.0? Wait. Maybe stream a movie? I can't be 100% sure, but the timing _does_ line up with me streaming a movie from a major service on my Xbox:
![image](https://user-images.githubusercontent.com/1923186/149788141-95e2b937-4bb9-42a5-85f7-23bdd0478947.png)

Point being there was a lot of network activity. That huge drop is when I stopped the addon.

## Proposed changes

Downgrade? I'm going to try this and see if it fixes the problem.

I can also attempt to repro again and get a memory dump, but might need some guidance on how to do that.

**Comment by frenck** [comment]
In the end, this add-on wraps an existing application. I'm not sure what the add-on could do about any of this.

That said, I don't see it happening on any of my devices at this moment.

**Comment by kevin-david** [comment]
Thanks - I assumed there was nothing special but wanted to confirm first, as well as see if anyone else had this issue with HASS, especially given folks are often running more resource constrained machines.

My rollback to 1.18.2 _seems_ to have worked and the device was stable overnight. I'll see if that holds true over the next few days and open an issue over at tailscale's repo if so.

**Comment by ahmadtawakol** [comment]
I'm having the exact same issue. Started happening a few days ago, right around when the add-on was updated to use version 1.20.0. Version 1.20.1 does not fix it either.

@frenck Since we can't downgrade the add-ons, is it possible to go back to using version 1.18.2 until this gets fixed by tailscale?

**Comment by frenck** [comment]
> Since we can't downgrade the add-ons, is it possible to go back to using version 1.18.2 until this gets fixed by tailscale?

Because it cannot do that. Hence it asks for making a backup before each update.

**Comment by ahmadtawakol** [comment]
It updated automatically, so I wasn't asked to create a backup.

But I was asking if you could downgrade the tailscale version that you use in this add-on.

**Comment by spaghettiScreen** [comment]
Can confirm this issue is happening to me too. 

Exact steps: Restart add-on (at this point, memory usage is minimal). Connect to Tailscale from another device, and send some data through the tunnel (for me, downloading a large file does the trick). At this point, the memory for the Tailscale container starts climbing steadily. 

I've noticed that the rate that memory use grows _seems_ to corresponds to the data throughput through the tunnel. A bit of a stab in the dark here, but _perhaps_ the data passing through the tunnel is being stored in some sort of buffer, and this isn't being cleared out...? Then again maybe it's just a run-of-the-mill memory leak, I'm not too sure.
